### PR TITLE
fix: v1.17.0 post-release fix-ups

### LINKED ISSUE #5659: v1.17.0 fails to build on NetBSD
#### Current Behavior
1.17.0 fails to build on NetBSD.

#### Expected Behavior
starship-1.17.0 builds on NetBSD, just as 1.16.0 did.

#### Additional context/Screenshots
System: NetBSD 10.99.10 (GENERIC) #0: Thu Dec 28 03:49:35 UTC 2023
Rust version: 1.74.1
Features: No default features, features notify

Build error:
```
[...]
   Compiling starship v1.17.0 (/usr/pkgsrc/wip/starship/work/starship-1.17.0)
   Compiling gix-config v0.32.0
   Compiling gix-index v0.27.0
error[E0609]: no field `st_mtime_nsec` on type `libc::stat`
  --> /usr/pkgsrc/wip/starship/work/vendor/gix-index-0.27.0/src/fs.rs:59:24
   |
59 |                 self.0.st_mtime_nsec.try_into().ok()?,
   |                        ^^^^^^^^^^^^^ help: a field with a similar name exists: `st_mtimensec`

error[E0609]: no field `st_ctime_nsec` on type `libc::stat`
  --> /usr/pkgsrc/wip/starship/work/vendor/gix-index-0.27.0/src/fs.rs:75:24
   |
75 |                 self.0.st_ctime_nsec.try_into().ok()?,
   |                        ^^^^^^^^^^^^^ help: a field with a similar name exists: `st_ctimensec`

For more information about this error, try `rustc --explain E0609`.
error: could not compile `gix-index` (lib) due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by davidkna**
#### Description

* `cargo update` to fix NetBSD builds (#5659)
* dprint: ignore `bn-BD` alongside the other translated docs.
* Downgrade node to v16 in `notarize_and_pkgbuild` to match `publish_docs`

#### Motivation and Context

May close #5659

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by andytom — APPROVED** [review]

**Comment by davidkna** [comment]
Thanks for the reviews @andytom!
